[server]
headless = true
port = 8006
enableCORS = true
enableXsrfProtection = true
enableWebsocketCompression = true
sslKeyFile = "./.streamlit/key.pem"
sslCertFile = "./.streamlit/cert.pem"
folderWatchBlacklist = ["./data","./dataset","./models"]

[logger]
level = "debug"

[browser]
gatherUsageStats = false
serverPort = 8006